// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPTBhAi2elGSCOIbp_lfA69IADfVc3bu0',
    appId: '1:490194759252:web:b4905191782e5ba42dc7c1',
    messagingSenderId: '490194759252',
    projectId: 'reddit-11bc7',
    authDomain: 'reddit-11bc7.firebaseapp.com',
    storageBucket: 'reddit-11bc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfhr8nUeERTdIHm0xw3MrueQV1c5PiKhM',
    appId: '1:490194759252:android:ffd935eb6b722e932dc7c1',
    messagingSenderId: '490194759252',
    projectId: 'reddit-11bc7',
    storageBucket: 'reddit-11bc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj2CuWSuRm_z7Uk-185zhmITaPNg8-ZzM',
    appId: '1:490194759252:ios:fb2dccc51a8aecfa2dc7c1',
    messagingSenderId: '490194759252',
    projectId: 'reddit-11bc7',
    storageBucket: 'reddit-11bc7.appspot.com',
    iosClientId: '490194759252-5o86e7o02mljb1c5earp2q04jjgm1km0.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj2CuWSuRm_z7Uk-185zhmITaPNg8-ZzM',
    appId: '1:490194759252:ios:fb2dccc51a8aecfa2dc7c1',
    messagingSenderId: '490194759252',
    projectId: 'reddit-11bc7',
    storageBucket: 'reddit-11bc7.appspot.com',
    iosClientId: '490194759252-5o86e7o02mljb1c5earp2q04jjgm1km0.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
